### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by pcercuei** [theZiz/sparrow3d#35]
```
/home/paul/dev/rs90/buildroot/output/gcw0/host/bin/mipsel-gcw0-linux-uclibc-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2   -DGCW -shared -Wl,-soname,libsparrow3d.so -rdynamic -o ./libsparrow3d.so sparrowFont.o sparrowCore.o sparrowMath.o sparrowPrimitives.o sparrowMesh.o sparrowSprite.o sparrowFile.o sparrowPrimitivesAsm.o sparrowRenderer.o sparrowText.o sparrowMapping.o sparrowParticles.o -I/home/paul/dev/rs90/buildroot/output/gcw0/host/mipsel-gcw0-linux-uclibc/sysroot/usr/bin/../../usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT   -I.   -lSDL_mixer -lSDL_ttf -lSDL_image -lSDL -lm -lSDL_net
/home/paul/dev/rs90/buildroot/output/gcw0/host/lib/gcc/mipsel-gcw0-linux-uclibc/10.2.0/../../../../mipsel-gcw0-linux-uclibc/bin/ld: sparrowMapping.o:(.bss+0xaf54): multiple definition of `__spMapDesktopHack'; sparrowCore.o:(.bss+0x4040): first defined here
/home/paul/dev/rs90/buildroot/output/gcw0/host/lib/gcc/mipsel-gcw0-linux-uclibc/10.2.0/../../../../mipsel-gcw0-linux-uclibc/bin/ld: sparrowMapping.o:(.bss+0xaa48): multiple definition of `__spMapDesktopButton'; sparrowCore.o:(.bss+0x4020): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:184: libsparrow3d.so] Error 1
make[1]: *** [package/pkg-generic.mk:250: /home/paul/dev/rs90/buildroot/output/gcw0/build/sparrow3d-14bcb69/.stamp_built] Error 2
make: *** [Makefile:84: _all] Error 2
```

Fix:
```
diff --git a/sparrowCore.c b/sparrowCore.c
index 97bb802..8056f83 100644
--- a/sparrowCore.c
+++ b/sparrowCore.c
@@ -86,8 +86,8 @@ char spWindowName[512] = "";
 int spVirtualKeyboardSpaceButton = -1;
 int spVirtualKeyboardBackspaceButton = -1;
 
-int __spMapDesktopHack;
-int __spMapDesktopButton[SP_MAPPING_MAX];
+extern int __spMapDesktopHack;
+extern int __spMapDesktopButton[SP_MAPPING_MAX];
 
 typedef struct sp_cache_struct *sp_cache_pointer;
 typedef struct sp_cache_struct {
```

**Comment by clort81** [comment]
What compiler?  Builds fine with gcc 8.3.0 here.

**Comment by pcercuei** [comment]
GCC 10.2.

**Comment by theZiz** [comment]
Hm, same with gcc 10.1
Tbh I guess I was drunken when I added this hack. :scream: 
I fixed it! :D
https://github.com/theZiz/sparrow3d/commit/2033349d7adeba34bda2c442e1fec22377471134

Hase had the same error btw -_-
